### ISSUE TITLE
Crash/blank page upon sim data retrieval : LNM 2.7.8.develop aircraft progress coordinates display turned off by default

### ISSUE THREAD

**Issue by KOKAProduktion** [KOKAProduktion/littlenavmap-openlayers#2]
However i've found another issue while testing this prototype with the latest LNM version:

- LNM 2.7.8.develop 
- MSFS 1.22.2.0

Aircraft progress coordinates display appears to be turned off by default since LNM 2.7.8 causing the OL prototype to crash as soon as sim data is coming in.

To fix this I had to check on "Coordinates" at Tools -> Progress Display Options:

![Screenshot (173)](https://user-images.githubusercontent.com/3401839/154784950-c1a0744e-c653-43a4-823e-326620bbf1d2.png)

![Screenshot (174)](https://user-images.githubusercontent.com/3401839/154784953-6b581b66-e2d7-46e5-bd0f-1eafd5c06742.png)

Hope this helps too... :)

Cheers!

_Originally posted by @KOKAProduktion in https://github.com/KOKAProduktion/msfs2020-littlenavmap-openlayers/issues/1#issuecomment-1045686608_

**Comment by albar965** [comment]
Fixed with albar965/littlenavmap@fdce0516e37301dec0debe27f0fe5769bf6a0a22
There is now a separate bitset for the web interface which has certain features like the coordinates always enabled.
Alex

**Comment by KOKAProduktion** [comment]
Hi @albar965,

wow cool, thx for the rapid fix! Sorry, I didn't mean to bother you with this, as i didn't see it as a bug on LNM side... That's just an issue for me :) I'll have to check coords parsing on my side and probably display a hint message instead of crashing. 

Nevertheless, thanks and cheers!

**Comment by KOKAProduktion** [comment]
Also this will become obsolete by introducing #1

**Comment by albar965** [comment]
Ahh. Stupid me. Thought it was assigned to me. I can revert the change if you want. :smile:

**Comment by KOKAProduktion** [comment]
No, you don't have to, since this workaround-retrieval becomes obsolete with the API anyway...
Thanks!

**Comment by albar965** [comment]
Right. I'm wondering anyway how you deal with the different coordinate formats which can be selected in LNM options.
JSON/REST API will simplify things a lot, I suppose.

**Comment by KOKAProduktion** [comment]
> ...how you deal with the different coordinate formats...

I don't :) I just assumed the DMS string format ("deg min sec dir, deg min sec dir") in progress_doc.html is constant until i've found out it's configureable via LNM settings. So it just "crashes" atm when no or another format is provided.
